/**
 * SPEC-019 §6 (revisada) — los 601 ejercicios reales de RepDB.
 *
 * Generado 1:1 desde el dataset público de RepDB (exercise-dataset.com),
 * columnas `id` (slug) y `name_es` — nada traducido ni tocado a mano.
 * Por eso vive separado de `TEMPLATE_EXERCISE_SLUGS`: es un dato, no una
 * decisión editorial (esa tabla sí lleva matices hechos a mano, como
 * distinguir «Remo con mancuerna» de «Remo inclinado con dos mancuernas»).
 *
 * Por ser datos y no lógica, no entra en mutation testing
 * (stryker.config.json): mutar 601 strings no prueba nada que los tests de
 * forma de exercise-library.test.ts no prueben ya (conteo, formato de
 * slug, nombres no vacíos). Lo que sí se muta es `exerciseUrl`, que es
 * donde vive la decisión de a cuál tabla mirar primero.
 *
 * El `name_es` de RepDB no sigue un único estilo de mayúsculas (aquí
 * conviven «Abdominales en Máquina Sentado» y «Zancada rotacional con
 * pesa rusa», ambos reales) — por eso `exerciseUrl` compara estos nombres
 * sin distinguir mayúsculas de minúsculas.
 */
export const REPDB_EXERCISE_SLUGS: Readonly<Record<string, string>> = {
  'Abdominal navaja': 'jackknife-sit-up',
  'Abdominales': 'sit-ups',
  'Abdominales en Máquina Sentado': 'machine-seated-crunch',
  'Abducción de Cadera Acostado de Lado': 'side-lying-hip-abduction',
  'Abducción de Cadera Acostado de Lado Isométrica': 'side-lying-hip-abduction-hold',
  'Abducción de Cadera de Pie con Banda': 'banded-standing-hip-abduction',
  'Abducción de Cadera en Máquina': 'hip-abduction',
  'Abducción de Cadera Sentado con Banda': 'banded-seated-hip-abduction',
  'Aducción de cadera': 'hip-adduction',
  'Aducción de Cadera Acostado de Lado': 'side-lying-hip-adduction',
  'Aducción de Cadera Acostado de Lado Isométrica': 'side-lying-hip-adduction-hold',
  'Aducción de Cadera de Pie con Banda': 'banded-standing-hip-adduction',
  'Agarre de Discos': 'plate-pinch',
  'Almeja con Banda': 'banded-clamshell',
  'Almejas': 'clamshells',
  'Almejas Isométricas': 'clamshells-hold',
  'Ángulo Lateral Extendido': 'extended-side-angle',
  'Apertura con mancuernas en banco inclinado': 'incline-dumbbell-fly',
  'Apertura de Deltoides Posterior': 'rear-delt-fly',
  'Aperturas con Cable': 'cable-fly',
  'Aperturas con Mancuernas': 'db-fly',
  'Aperturas con Mancuernas en Banco Declinado': 'decline-db-fly',
  'Aperturas en Máquina': 'machine-chest-fly',
  'Arrancada': 'snatch',
  'Back lever': 'back-lever',
  'Balanceo de Flexor de Cadera en Media Rodilla': 'half-kneeling-hip-flexor-rock',
  'Bicicleta de Aire': 'air-bike',
  'Bicicleta Estática': 'stationary-bike',
  'Bird-Dog': 'bird-dog',
  'Bird-Dog Isométrico': 'bird-dog-hold',
  'Buenos Días': 'good-morning',
  'Buenos Días con Banda': 'banded-good-morning',
  'Buenos Días con Peso Corporal': 'bodyweight-good-morning',
  'Buenos Días en Máquina Smith': 'smith-machine-good-morning',
  'Burpees': 'burpees',
  'Caminar': 'walking',
  'Caminata del Granjero con Mancuernas': 'dumbbell-farmers-walk',
  'Caminata del Oso': 'bear-crawl',
  'Caminata en Cinta Inclinada': 'incline-treadmill-walk',
  'Caminata Lateral con Banda': 'banded-lateral-walk',
  'Caminata Sumo con Banda': 'banded-sumo-walk',
  'Cargada desde Colgante': 'hang-clean',
  'Carrera en Cinta': 'treadmill-running',
  'Clean': 'clean',
  'Clean and Jerk': 'clean-and-jerk',
  'Clean and press con doble kettlebell': 'double-kettlebell-clean-and-press',
  'Clean con Dos Pesas Rusas': 'double-kettlebell-clean',
  'Cocoons': 'cocoons',
  'Colgado Pasivo': 'dead-hang',
  'Correr': 'running',
  'Crunch con Cable': 'cable-crunch',
  'Crunch Cruzado': 'cross-body-crunch',
  'Crunch de Bicicleta': 'bicycle-crunch',
  'Crunch Declinado': 'decline-crunch',
  'Crunch en Pared con Peso': 'weighted-wall-crunch',
  'Crunches': 'crunches',
  'Crunches Inversos': 'reverse-crunches',
  'Cuelgue Estático en Anillas': 'ring-dead-hang',
  'Cuerdas de Batalla': 'battle-ropes',
  'Curl Araña': 'spider-curl',
  'Curl con Barra': 'barbell-curl',
  'Curl con Barra Z': 'ez-bar-curl',
  'Curl con Barra Z y Agarre Cerrado': 'close-grip-ez-bar-curl',
  'Curl con Cable': 'cable-curl',
  'Curl con Impulso': 'cheat-curl',
  'Curl con mancuernas en banco inclinado': 'incline-db-curl',
  'Curl con Mancuernas Sentado': 'seated-dumbbell-curl',
  'Curl de Barra con Agarre Cerrado': 'close-grip-barbell-curl',
  'Curl de Bíceps con Dos Pesas Rusas': 'double-kettlebell-bicep-curl',
  'Curl de Bíceps con Mancuernas': 'bicep-curl',
  'Curl de Bíceps con Pesa Rusa a Un Brazo': 'one-arm-kettlebell-bicep-curl',
  'Curl de Bíceps en Máquina': 'machine-bicep-curl',
  'Curl de Bíceps TRX': 'trx-bicep-curl',
  'Curl de Concentración': 'concentration-curl',
  'Curl de concentración con kettlebell': 'kettlebell-concentration-curl',
  'Curl de Isquiotibiales con TRX': 'trx-hamstring-curl',
  'Curl de Martillo con Mancuernas': 'hammer-curl',
  'Curl de Martillo en Cable': 'cable-hammer-curl',
  'Curl de Muñeca con Barra': 'barbell-wrist-curl',
  'Curl de Muñeca con Barra Z': 'ez-bar-wrist-curl',
  'Curl de Muñeca con Cable': 'cable-wrist-curl',
  'Curl de Muñeca con Kettlebell': 'kettlebell-wrist-curl',
  'Curl de Muñeca con Mancuerna': 'dumbbell-wrist-curl',
  'Curl de Muñeca con Mancuernas Bilateral': 'wrist-curl',
  'Curl de Muñeca Inverso con Kettlebell': 'kettlebell-reverse-wrist-curl',
  'Curl de Muñeca Inverso con Mancuerna': 'db-reverse-wrist-curl',
  'Curl de Pierna de Pie con Banda': 'banded-standing-curl',
  'Curl de Pierna Tumbado a Una Pierna': 'single-leg-lying-leg-curl',
  'Curl de Piernas con Pelota de Estabilidad': 'ball-leg-curl',
  'Curl de Piernas Sentado': 'seated-leg-curl',
  'Curl de Piernas Tumbado': 'leg-curl',
  'Curl en Banco Scott': 'preacher-curl',
  'Curl en Máquina de Predicador': 'machine-preacher-curl',
  'Curl Estricto': 'strict-curl',
  'Curl Inverso': 'reverse-curl',
  'Curl Inverso con Barra Z': 'ez-bar-reverse-curl',
  'Curl Inverso con Mancuernas': 'db-reverse-curl',
  'Curl martillo con pesa rusa': 'kettlebell-hammer-curl',
  'Curl Martillo Cruzado': 'cross-body-hammer-curl',
  'Curl martillo en banco inclinado': 'incline-hammer-curl',
  'Curl Martillo en Banco Scott': 'preacher-hammer-curl',
  'Curl martillo unilateral': 'single-arm-hammer-curl',
  'Curl Nórdico de Isquiotibiales': 'nordic-hamstring-curl',
  'Curl Predicador con Barra': 'barbell-preacher-curl',
  'Curl Zottman': 'zottman-curl',
  'Dead Bug': 'dead-bug',
  'Dead Bug Isométrico': 'dead-bug-hold',
  'Dead Clean con Dos Pesas Rusas': 'double-kettlebell-dead-clean',
  'Dead Split Snatch con Dos Pesas Rusas': 'double-kettlebell-dead-split-snatch',
  'Dominada': 'pull-up',
  'Dominada con Pausa': 'pause-pull-up',
  'Dominada Lastrada': 'weighted-pull-up',
  'Dominada tras nuca': 'behind-the-neck-pull-ups',
  'Dominadas Arquero': 'archer-pull-ups',
  'Dominadas Asistidas': 'assisted-pull-ups',
  'Dominadas Asistidas con Banda': 'band-assisted-pull-ups',
  'Dominadas con Agarre Cerrado': 'close-grip-pull-ups',
  'Dominadas en Agarre Ancho': 'wide-grip-pull-ups',
  'Dominadas en Agarre Neutro': 'neutral-grip-pull-ups',
  'Dominadas en Supinación': 'chin-ups',
  'Dominadas Escapulares': 'scapular-pull-ups',
  'Dominadas Negativas': 'negative-pull-ups',
  'Drag Curl': 'drag-curl',
  'Dragon Flag': 'dragon-flag',
  'Elevación de Pantorrilla a la Burra': 'donkey-calf-raise',
  'Elevación de Pantorrilla a la Burra en Máquina': 'plate-loaded-donkey-calf-raise',
  'Elevación de Pantorrilla a Una Pierna': 'single-leg-calf-raise',
  'Elevación de Pantorrillas en Máquina': 'machine-calf-raise',
  'Elevación de Piernas Acostado': 'lying-leg-raise',
  'Elevación de Piernas Colgado': 'hanging-leg-raise',
  'Elevación de Piernas en Silla Romana': 'captains-chair-leg-raise',
  'Elevación de Rodillas Colgado': 'hanging-knee-raise',
  'Elevación de Rodillas en Silla Romana': 'captains-chair-knee-raise',
  'Elevación de Talón en Máquina Smith': 'smith-machine-calf-raise',
  'Elevación de Talones con Barra': 'barbell-calf-raise',
  'Elevación de Talones con Mancuernas': 'dumbbell-calf-raise',
  'Elevación de Talones con Peso Corporal': 'bodyweight-calf-raise',
  'Elevación de Talones de Pie': 'standing-calf-raise',
  'Elevación de Talones en Máquina Hack Squat': 'hack-squat-calf-raise',
  'Elevación de Talones Sentado': 'seated-calf-raise',
  'Elevación Frontal con Barra': 'barbell-front-raise',
  'Elevación Frontal con Barra Z': 'ez-bar-front-raise',
  'Elevación Frontal con Cable': 'cable-front-raise',
  'Elevación Frontal con Mancuernas': 'dumbbell-front-raise',
  'Elevación frontal en polea con barra recta': 'straight-bar-cable-front-raise',
  'Elevación Lateral a Un Brazo en Máquina de Discos': 'single-arm-plate-loaded-lateral-raise',
  'Elevación Lateral con Mancuerna Sentado': 'seated-dumbbell-lateral-raise',
  'Elevación Lateral con Mancuernas': 'lateral-raise',
  'Elevación Lateral con Peso Corporal': 'bodyweight-lateral-raise',
  'Elevación Lateral en Máquina de Discos': 'plate-loaded-lateral-raise',
  'Elevación Lateral en Polea': 'cable-lateral-raise',
  'Elevación Lateral Tumbado de Lado': 'side-lying-lateral-raise',
  'Elíptica': 'elliptical-trainer',
  'Empuje de Cadera Arrodillado con Banda': 'banded-kneeling-hip-thrust',
  'Empuje de Cadera con Banda': 'banded-hip-thrust',
  'Empuje de Cadera con Kettlebell': 'kettlebell-hip-thrust',
  'Empuje de Cadera con Mancuerna': 'dumbbell-hip-thrust',
  'Empuje de Glúteo en Máquina de Discos': 'plate-loaded-glute-drive',
  'Encogimiento con Barra': 'shrug',
  'Encogimiento de Hombros con Barra Detrás de la Espalda': 'behind-the-back-barbell-shrug',
  'Encogimiento de Hombros con Barra Z': 'ez-bar-shrug',
  'Encogimiento de Hombros con Kettlebell': 'kettlebell-shrug',
  'Encogimiento de Hombros con Mancuernas': 'db-shrug',
  'Encogimiento de Hombros con Mancuernas y Apoyo en el Pecho': 'chest-supported-dumbbell-shrug',
  'Encogimiento de Hombros en Máquina de Discos': 'plate-loaded-shrug',
  'Encogimiento de Hombros en Máquina Smith': 'smith-machine-shrug',
  'Encogimiento de Piernas en Banco': 'bench-leg-pull-in',
  'Encogimiento de Rodillas con Balón de Estabilidad': 'stability-ball-knee-tuck',
  'Enhebrar la Aguja': 'thread-the-needle',
  'Enhebrar la Aguja Dinámico': 'thread-the-needle-flow',
  'Escaladora de Escaleras': 'stair-climber',
  'Estiramiento Búlgaro en Banco': 'bench-bulgarian-split-stretch',
  'Estiramiento Couch en Banco': 'bench-couch-stretch',
  'Estiramiento de Aductores con Banda': 'banded-adductor-stretch',
  'Estiramiento de Aductores en Banco': 'bench-adductor-stretch',
  'Estiramiento de Banda Iliotibial con Banda': 'banded-it-band-stretch',
  'Estiramiento de Cuádriceps de Pie': 'standing-quad-stretch',
  'Estiramiento de Deltoides Posterior con Banda': 'banded-rear-delt-stretch',
  'Estiramiento de Dorsales con Banda': 'banded-lat-stretch',
  'Estiramiento de Dorsales en Banco': 'bench-lat-stretch',
  'Estiramiento de Flexores de Cadera Arrodillado': 'kneeling-hip-flexor-stretch',
  'Estiramiento de Hombro Cruzado': 'cross-body-shoulder-stretch',
  'Estiramiento de Hombros con Banda': 'banded-shoulder-stretch',
  'Estiramiento de Isquiotibiales con Banda': 'banded-hamstring-stretch',
  'Estiramiento de Isquiotibiales en Banco': 'bench-hamstring-stretch',
  'Estiramiento de la Cobra': 'cobra-stretch',
  'Estiramiento de la Paloma': 'pigeon-stretch',
  'Estiramiento de Mariposa': 'butterfly-stretch',
  'Estiramiento de Muñecas Arrodillado': 'kneeling-wrist-stretch',
  'Estiramiento de Pantorrilla con Banda': 'banded-calf-stretch',
  'Estiramiento de Pantorrilla de Pie': 'standing-calf-stretch',
  'Estiramiento de Pantorrilla en Banco': 'bench-calf-stretch',
  'Estiramiento de Pecho con Banda': 'banded-chest-stretch',
  'Estiramiento de Pecho en Banco': 'bench-chest-stretch',
  'Estiramiento de Pecho en el Marco': 'doorway-chest-stretch',
  'Estiramiento de Tobillo con Banda': 'banded-ankle-stretch',
  'Estiramiento de Tobillo en Banco': 'bench-ankle-stretch',
  'Estiramiento de Tríceps con Banda': 'banded-triceps-stretch',
  'Estiramiento de Tríceps sobre la Cabeza': 'overhead-triceps-stretch',
  'Estiramiento del Gato': 'cat-stretch',
  'Estiramiento del Lagarto': 'lizard-stretch',
  'Estiramiento en Apertura Sentado': 'seated-straddle-stretch',
  'Estiramiento Figura 4 con Banda': 'banded-figure-4-stretch',
  'Estiramiento Figura 4 de Glúteos en Banco': 'bench-figure-4-glute-stretch',
  'Estiramiento Lateral de Cuello': 'neck-side-stretch',
  'Estiramiento Rodilla al Pecho': 'knee-to-chest-stretch',
  'Extensión de Barra por Encima de la Cabeza': 'barbell-overhead-extension',
  'Extensión de Cuádriceps a Una Pierna': 'single-leg-extension',
  'Extensión de Espalda': 'back-extension',
  'Extensión de Espalda en Máquina': 'machine-back-extension',
  'Extensión de Piernas': 'leg-extension',
  'Extensión de Tríceps a Un Brazo con Pesa Rusa': 'one-arm-kettlebell-tricep-kickback',
  'Extensión de Tríceps a Un Brazo en Polea': 'single-arm-tricep-pushdown',
  'Extensión de Tríceps con Mancuerna': 'dumbbell-tricep-extension',
  'Extensión de Tríceps con Mancuerna Sentado': 'seated-dumbbell-tricep-extension',
  'Extensión de Tríceps en Máquina': 'machine-triceps-extension',
  'Extensión de Tríceps en Polea con Barra en V': 'v-bar-tricep-pushdown',
  'Extensión de Tríceps por Encima de la Cabeza': 'overhead-tricep-extension',
  'Extensión de Tríceps por Encima de la Cabeza con Barra Z': 'ez-bar-overhead-extension',
  'Extensión de tríceps por encima de la cabeza con pesa rusa': 'kettlebell-overhead-tricep-extension',
  'Extensión de Tríceps sobre la Cabeza con Mancuerna a Un Brazo': 'single-arm-dumbbell-overhead-tricep-extension',
  'Extensión de Tríceps TRX': 'trx-tricep-extension',
  'Extensión de Tríceps Tumbado': 'lying-tricep-extension',
  'Extensión de Tríceps Tumbado con Barra Z': 'ez-bar-lying-tricep-extension',
  'Extensión Terminal de Rodilla con Banda': 'banded-terminal-knee-extension',
  'Face Pull con Mancuernas': 'dumbbell-face-pull',
  'Face Pull con TRX': 'trx-face-pull',
  'Face Pull en Anillas': 'ring-face-pull',
  'Face Pull en Polea': 'face-pull',
  'Flexión con Piernas Abiertas': 'wide-legged-forward-fold',
  'Flexión de Pie a Media Elevación': 'standing-forward-fold-to-half-lift',
  'Flexión de Pie hacia Adelante': 'standing-forward-fold',
  'Flexión Declinada': 'decline-push-up',
  'Flexión en Anillas': 'ring-push-up',
  'Flexión Lateral con Mancuerna': 'dumbbell-side-bend',
  'Flexión Lateral de Pie': 'standing-side-bend',
  'Flexión Lateral de Pie Alterna': 'standing-side-bend-flow',
  'Flexión Lateral de Pilates': 'pilates-side-bend',
  'Flexión Lateral Isométrica de Cuello': 'isometric-neck-side',
  'Flexión Pliométrica': 'plyo-push-up',
  'Flexión Sentado hacia Adelante': 'seated-forward-fold',
  'Flexión sobre pelota de estabilidad (manos en la pelota)': 'stability-ball-push-up-hands-on-ball',
  'Flexiones con Agarre Ancho': 'wide-grip-push-ups',
  'Flexiones con Agarre Cerrado': 'close-grip-push-ups',
  'Flexiones con Palmada': 'clap-push-ups',
  'Flexiones en Déficit': 'deficit-push-ups',
  'Flexiones en Diamante': 'diamond-push-ups',
  'Flexiones en Pica': 'pike-push-ups',
  'Flexiones en Pino': 'handstand-push-ups',
  'Flutter Kicks': 'flutter-kicks',
  'Fondos de Cangrejo': 'crab-dips',
  'Fondos en Anillas': 'ring-dips',
  'Fondos en Banco': 'bench-dips',
  'Fondos en Barra Recta': 'straight-bar-dips',
  'Fondos en Máquina Asistida': 'assisted-dips',
  'Fondos en Plancha Invertida': 'reverse-plank-dips',
  'Fondos Lastrados': 'weighted-dips',
  'Fondos para Pecho': 'dips',
  'Front Lever': 'front-lever',
  'Gato-Vaca': 'cat-cow',
  'Giro Espinal Sentado': 'seated-spinal-twist',
  'Giro Espinal Tumbado': 'supine-spinal-twist',
  'Giro Ruso': 'russian-twist',
  'Giro ruso con pesa rusa': 'kettlebell-russian-twist',
  'Golpe con Balón Medicinal': 'medicine-ball-slam',
  'Golpe Doble con Cuerdas de Batalla': 'battle-rope-double-slam',
  'Guerrero I': 'warrior-one',
  'Guerrero II': 'warrior-two',
  'Guerrero III': 'warrior-three',
  'Hack Squat': 'hack-squat',
  'Halo con pesa rusa': 'kettlebell-halo',
  'Hidrante de Fuego con Banda': 'banded-fire-hydrant',
  'Hip thrust con barra': 'hip-thrust',
  'Hip Thrust en Máquina Smith': 'smith-machine-hip-thrust',
  'Human Flag': 'human-flag',
  'Jalón al Cuello Detrás de la Cabeza': 'behind-the-neck-lat-pulldown',
  'Jalón al Pecho': 'lat-pulldown',
  'Jalón al Pecho Agarre Supino': 'reverse-grip-lat-pulldown',
  'Jalón al Pecho con Agarre Cerrado': 'close-grip-lat-pulldown',
  'Jalón al Pecho con Barra en V': 'v-bar-lat-pulldown',
  'Jalón al Pecho con Un Brazo': 'one-arm-lat-pulldown',
  'Jalón con Brazos Rectos': 'straight-arm-pulldown',
  'Jalón de Tríceps en Cable': 'tricep-pushdown',
  'Jalón sumo al mentón con pesa rusa': 'kettlebell-sumo-high-pull',
  'Jefferson curl': 'jefferson-curl',
  'Jerk con Dos Pesas Rusas': 'double-kettlebell-jerk',
  'Jerk con Tijera': 'split-jerk',
  'Jerk de Empuje': 'push-jerk',
  'L-Sit': 'l-sit',
  'La Sierra de Pilates': 'pilates-saw',
  'Leg Pull Back de Pilates': 'pilates-leg-pull-back',
  'Leg Pull Front de Pilates': 'pilates-leg-pull-front',
  'Levantamiento Turco con Kettlebell': 'kettlebell-turkish-get-ups',
  'Limpiaparabrisas Tumbado': 'supine-windshield-wipers',
  'Mantenimiento del Cuerpo Hueco': 'hollow-body-hold',
  'Máquina de Remo': 'rowing-machine',
  'Marcha en Tándem': 'heel-to-toe-walk',
  'Mesa Invertida Isométrica': 'reverse-tabletop-hold',
  'Molino con Mancuerna': 'dumbbell-windmill',
  'Molino de Viento con Pesa Rusa': 'kettlebell-windmills',
  'Mountain Climbers': 'mountain-climbers',
  'Muscle Snatch': 'muscle-snatch',
  'Muscle-Up en Anillas': 'ring-muscle-up',
  'Muscle-Ups': 'muscle-ups',
  'Nordic Curl Inverso': 'reverse-nordic-curl',
  'Pájaro Invertido con Mancuernas': 'dumbbell-reverse-fly',
  'Paseo con Dos Kettlebells sobre la Cabeza': 'double-kettlebell-overhead-carry',
  'Paseo con Dos Mancuernas sobre la Cabeza': 'double-db-overhead-carry',
  'Paseo con Kettlebell sobre la Cabeza': 'kettlebell-overhead-carry',
  'Paseo con Mancuerna sobre la Cabeza': 'db-overhead-carry',
  'Paseo del Granjero con Pesa Rusa': 'kettlebell-farmers-walk',
  'Paseo del Maletín': 'suitcase-carry',
  'Patada de Glúteo': 'glute-kickback',
  'Patada de Glúteo Isométrica': 'glute-kickback-hold',
  'Patada de Tríceps con Cable': 'cable-tricep-kickback',
  'Patada de Tríceps con Mancuerna': 'tricep-kickback',
  'Patada Lateral de Rodillas de Pilates': 'pilates-kneeling-side-kick',
  'Patada Trasera de Glúteos en Cable': 'cable-kickback',
  'Pec Deck': 'pec-deck',
  'Pedaleo en Perro Boca Abajo': 'downward-dog-pedal',
  'Perro Boca Abajo': 'downward-dog',
  'Perro Boca Abajo a Perro Boca Arriba': 'downward-dog-to-upward-dog',
  'Perro Boca Abajo a Plancha': 'downward-dog-to-plank',
  'Perro Boca Abajo a Zancada Baja': 'downward-dog-to-low-lunge',
  'Perro Boca Arriba': 'upward-dog',
  'Perro de Tres Patas': 'three-legged-dog',
  'Peso muerto a una pierna con pesa rusa': 'kettlebell-single-leg-deadlift',
  'Peso Muerto con Barra': 'deadlift',
  'Peso Muerto con Barra Hexagonal': 'hex-bar-deadlift',
  'Peso Muerto con Mancuernas': 'dumbbell-deadlift',
  'Peso Muerto con Pausa': 'pause-deadlift',
  'Peso muerto con pesa rusa': 'kettlebell-deadlift',
  'Peso Muerto con Piernas Rígidas': 'stiff-leg-deadlift',
  'Peso Muerto en Déficit': 'deficit-deadlift',
  'Peso Muerto Kickstand con Doble Mancuerna': 'double-db-kickstand-deadlift',
  'Peso Muerto Kickstand con Kettlebell': 'kettlebell-kickstand-deadlift',
  'Peso Muerto Kickstand con Mancuerna': 'db-kickstand-deadlift',
  'Peso Muerto Rumano': 'romanian-deadlift',
  'Peso Muerto Rumano a Una Pierna': 'single-leg-romanian-deadlift',
  'Peso Muerto Rumano a Una Pierna con Mancuerna a Un Brazo': 'one-arm-single-leg-dumbbell-romanian-deadlift',
  'Peso Muerto Rumano a Una Pierna con Pesa Rusa a Un Brazo': 'one-arm-single-leg-kettlebell-romanian-deadlift',
  'Peso Muerto Rumano con Banda': 'banded-romanian-deadlift',
  'Peso Muerto Rumano con Barra Z': 'ez-bar-romanian-deadlift',
  'Peso Muerto Rumano con Mancuernas': 'dumbbell-romanian-deadlift',
  'Peso Muerto Rumano en Máquina Smith': 'smith-machine-rdl',
  'Peso Muerto Sumo': 'sumo-deadlift',
  'Peso muerto sumo con pesa rusa': 'kettlebell-sumo-deadlift',
  'Piernas en la Pared': 'legs-up-the-wall',
  'Pike Colgado': 'hanging-pike',
  'Pike con Pelota': 'ball-pike',
  'Plancha': 'plank',
  'Plancha Alta': 'high-plank',
  'Plancha Calisténica': 'planche',
  'Plancha en TRX': 'trx-plank',
  'Plancha Inversa': 'reverse-plank',
  'Plancha Lateral': 'side-plank',
  'Plancha Lateral con Elevación de Pierna': 'side-plank-leg-lift',
  'Plancha Lateral con Elevación de Pierna Isométrica': 'side-plank-leg-lift-hold',
  'Plancha Lateral en TRX': 'trx-side-plank',
  'Posición en V': 'v-sit',
  'Postura de Cabeza a la Rodilla': 'head-to-knee-pose',
  'Postura de la Cara de Vaca': 'cow-face-pose',
  'Postura de la Esfinge': 'sphinx-pose',
  'Postura de la Guirnalda': 'garland-pose',
  'Postura de la Media Luna': 'half-moon-pose',
  'Postura de la Montaña': 'mountain-pose',
  'Postura de la Pirámide': 'pyramid-pose',
  'Postura de la Silla': 'chair-pose',
  'Postura de la Silla Girada': 'revolved-chair-pose',
  'Postura del Águila': 'eagle-pose',
  'Postura del Arado': 'plow-pose',
  'Postura del Árbol': 'tree-pose',
  'Postura del Arco': 'bow-pose',
  'Postura del Bailarín': 'dancer-pose',
  'Postura del Barco': 'boat-pose',
  'Postura del Bebé Feliz': 'happy-baby',
  'Postura del Cachorro': 'puppy-pose',
  'Postura del Cadáver': 'savasana',
  'Postura del Camello': 'camel-pose',
  'Postura del Cuervo': 'crow-pose',
  'Postura del Delfín': 'dolphin-pose',
  'Postura del Héroe': 'hero-pose',
  'Postura del Niño': 'childs-pose',
  'Postura del Niño en Banco': 'bench-childs-pose',
  'Postura del Pez': 'fish-pose',
  'Postura del Saltamontes': 'locust-pose',
  'Postura del Triángulo': 'triangle-pose',
  'Postura Fácil': 'easy-pose',
  'Power Clean desde Colgante': 'hang-power-clean',
  'Prensa de Piernas': 'leg-press',
  'Prensa de Piernas a Una Pierna': 'single-leg-press',
  'Prensa de piernas con pies altos': 'high-foot-leg-press',
  'Prensa de piernas con postura amplia': 'wide-stance-leg-press',
  'Prensa de piernas con postura cerrada': 'close-stance-leg-press',
  'Prensa de piernas horizontal': 'horizontal-leg-press',
  'Press Arnold': 'arnold-press',
  'Press con mancuernas en banco inclinado': 'incline-db-press',
  'Press de Banca con Agarre Cerrado': 'close-grip-bench-press',
  'Press de Banca con Barra': 'bench-press',
  'Press de Banca con Barra Z': 'ez-bar-bench-press',
  'Press de Banca con Barra Z y Agarre Cerrado': 'close-grip-ez-bar-bench-press',
  'Press de Banca con Mancuernas': 'db-bench-press',
  'Press de Banca con Mancuernas y Agarre Cerrado': 'close-grip-db-bench-press',
  'Press de Banca con Pausa': 'paused-bench-press',
  'Press de Banca Declinado': 'decline-bench-press',
  'Press de Banca Declinado con Barra': 'decline-bench-press-barbell',
  'Press de Banca Declinado con Barra Z': 'decline-bench-press-ez-bar',
  'Press de Banca Declinado en Máquina Smith': 'smith-machine-decline-bench-press',
  'Press de Banca en Agarre Ancho': 'wide-grip-bench-press',
  'Press de Banca en Máquina Smith': 'smith-machine-bench-press',
  'Press de Banca Inclinado con Agarre Cerrado': 'close-grip-incline-bench',
  'Press de Barra sobre la Cabeza Sentado': 'seated-barbell-overhead-press',
  'Press de Empuje': 'push-press',
  'Press de Empuje con Mancuernas': 'dumbbell-push-press',
  'Press de Hombro con Mancuernas Sentado': 'seated-db-press',
  'Press de Hombro con Pesa Rusa a Un Brazo': 'one-arm-kettlebell-shoulder-press',
  'Press de Hombros con Mancuernas': 'dumbbell-shoulder-press',
  'Press de Hombros en Máquina': 'machine-shoulder-press',
  'Press de Hombros en Máquina Smith': 'smith-machine-shoulder-press',
  'Press de Hombros en Máquina Smith Sentado': 'seated-smith-machine-shoulder-press',
  'Press de hombros unilateral en máquina': 'single-arm-machine-shoulder-press',
  'Press de Pecho con Cable': 'cable-chest-press',
  'Press de Pecho con TRX': 'trx-chest-press',
  'Press de Pecho en Máquina': 'chest-press-machine',
  'Press de Suelo con Agarre Cerrado con Pesa Rusa': 'kettlebell-close-grip-floor-press',
  'Press de Suelo con Mancuernas': 'dumbbell-floor-press',
  'Press de suelo con pesas rusas': 'kettlebell-floor-press',
  'Press Detrás del Cuello': 'behind-the-neck-press',
  'Press en banco inclinado con barra': 'incline-bench-press',
  'Press en banco inclinado con barra Z': 'incline-bench-ez-bar-press',
  'Press en Puente de Glúteos en Suelo con Pesa Rusa a Un Brazo': 'one-arm-kettlebell-floor-glute-bridge-press',
  'Press en Suelo': 'floor-press',
  'Press en Suelo con Barra Z': 'floor-ez-bar-press',
  'Press en Suelo con Pesa Rusa a Un Brazo': 'one-arm-kettlebell-floor-press',
  'Press Inclinado con Pausa': 'paused-incline-bench-press',
  'Press Inclinado en Máquina Smith': 'smith-machine-incline-bench-press',
  'Press Landmine': 'landmine-press',
  'Press Landmine con Un Brazo': 'one-arm-landmine-press',
  'Press Militar con Barra': 'ohp',
  'Press militar con pausa': 'paused-ohp',
  'Press Pallof en Polea': 'cable-pallof-press',
  'Press por Encima de la Cabeza con Dos Pesas Rusas': 'double-kettlebell-overhead-press',
  'Press por Encima de la Cabeza con Peso Corporal': 'bodyweight-overhead-press',
  'Press Spoto': 'spoto-press',
  'Press Strict con Pesa Rusa Invertida a Un Brazo': 'one-arm-kettlebell-bottoms-up-press',
  'Press Svend': 'svend-press',
  'Press Svend con Kettlebells': 'kettlebell-svend-press',
  'Press Svend con Mancuernas': 'db-svend-press',
  'Press Svend con una Mancuerna': 'single-db-svend-press',
  'Puente de Cadera con Balón de Estabilidad': 'stability-ball-hip-bridge',
  'Puente de Glúteo a Una Pierna': 'single-leg-glute-bridge',
  'Puente de Glúteo a Una Pierna Isométrico': 'single-leg-glute-bridge-hold',
  'Puente de Glúteos': 'glute-bridge',
  'Puente de Glúteos con Banda': 'banded-glute-bridge',
  'Puente de Glúteos con Barra': 'barbell-glute-bridge',
  'Puente de Glúteos Isométrico': 'glute-bridge-hold',
  'Puente Torácico': 'thoracic-bridge',
  'Pullover con Barra': 'barbell-pullover',
  'Pullover con Barra EZ': 'ez-bar-pullover',
  'Pullover con Barra y Brazos Flexionados': 'bent-arm-barbell-pullover',
  'Pullover con Barra Z y Brazos Flexionados': 'bent-arm-ez-bar-pullover',
  'Pullover con Disco': 'plate-pullover',
  'Pullover con Mancuerna': 'db-pullover',
  'Pullover con pesa rusa': 'kettlebell-pullover',
  'Pullover con Pesa Rusa en Suelo': 'floor-kettlebell-pullover',
  'Pulsos de Cadera en Mesa Invertida': 'reverse-tabletop-hip-pulses',
  'Push Press con Dos Pesas Rusas': 'double-kettlebell-push-press',
  'Push Press con Mancuerna a Un Brazo': 'one-arm-dumbbell-push-press',
  'Push Press con Pesa Rusa a Un Brazo': 'one-arm-kettlebell-push-press',
  'Push-Up': 'push-up',
  'Push-Up con Balón de Estabilidad': 'stability-ball-push-up',
  'Push-Up en Rodillas': 'knee-push-ups',
  'Push-up inclinado': 'incline-push-ups',
  'Push-Ups Arquero': 'archer-push-ups',
  'Push-Ups de Pseudo Plancha': 'pseudo-planche-push-ups',
  'Push-Ups en Pared': 'wall-push-ups',
  'Rack Pull': 'rack-pull',
  'Remo al Mentón con Barra': 'upright-row',
  'Remo al Mentón con Barra Z': 'ez-bar-upright-row',
  'Remo al Mentón con Cable': 'cable-upright-row',
  'Remo al Mentón con Mancuernas': 'dumbbell-upright-row',
  'Remo al Mentón en Máquina Smith': 'smith-machine-upright-row',
  'Remo con Apoyo en el Pecho en Máquina Smith': 'chest-supported-smith-machine-row',
  'Remo con Barra EZ y Agarre Supino': 'ez-bar-reverse-grip-row',
  'Remo con Barra Inclinado': 'barbell-row',
  'Remo con Barra para Deltoides Posterior': 'barbell-rear-delt-row',
  'Remo con Barra Z Inclinado': 'bent-over-ez-bar-row',
  'Remo con Dos Pesas Rusas': 'double-kettlebell-row',
  'Remo con Dos Pesas Rusas para Deltoides Posterior': 'double-kettlebell-rear-delt-row',
  'Remo con Kettlebell Apoyado en el Pecho': 'chest-supported-kettlebell-row',
  'Remo con Mancuerna a Un Brazo': 'single-arm-db-row',
  'Remo con Mancuerna a Una Mano con Pecho Apoyado': 'single-arm-chest-supported-dumbbell-row',
  'Remo con Mancuernas con Apoyo en el Pecho': 'chest-supported-db-row',
  'Remo con Mancuernas Inclinado': 'bent-over-db-row',
  'Remo con Pesa Rusa a Un Brazo': 'one-arm-kettlebell-row',
  'Remo con Trineo': 'sled-row',
  'Remo en Anillas': 'ring-row',
  'Remo en Banco': 'bench-pull',
  'Remo en Banco con Mancuernas': 'dumbbell-bench-pull',
  'Remo en Polea Arrodillado': 'kneeling-cable-row',
  'Remo en Polea Sentado en Agarre Ancho': 'wide-grip-seated-cable-row',
  'Remo en T': 't-bar-row',
  'Remo Inclinado con Agarre Inverso en Máquina Smith': 'smith-machine-reverse-grip-bent-over-row',
  'Remo Inclinado con Agarre Invertido': 'reverse-grip-bent-over-row',
  'Remo Inclinado con Cable': 'cable-bent-over-row',
  'Remo Inclinado en Máquina Smith': 'smith-machine-bent-over-row',
  'Remo invertido': 'inverted-row',
  'Remo Invertido en Anillas': 'rings-inverted-row',
  'Remo Pendlay': 'pendlay-row',
  'Remo Sentado en Polea': 'seated-cable-row',
  'Remo TRX': 'trx-row',
  'Retracción de Mentón Sostenida': 'chin-tuck-hold',
  'Rodilla al Codo desde Perro de Tres Patas': 'downward-dog-to-knee-drive',
  'Rodilla al Pecho en Perro Boca Abajo': 'downward-dog-knee-tuck',
  'Rodillas Altas': 'high-knees',
  'Rodillo de Muñeca': 'wrist-roller',
  'Roll Down de Pilates': 'pilates-roll-down',
  'Roll Over de Pilates': 'pilates-roll-over',
  'Rotación Externa con Cable': 'cable-external-rotation',
  'Rueda Abdominal': 'ab-wheel-rollout',
  'Rueda Abdominal con Barra': 'barbell-ab-rollout',
  'Saltar la Cuerda': 'jump-rope',
  'Salto al Cajón': 'box-jump',
  'Saltos de Tijera': 'jumping-jacks',
  'Sentadilla a una Pierna (Pistol)': 'pistol-squat',
  'Sentadilla Búlgara': 'bulgarian-split-squat',
  'Sentadilla Búlgara con Kettlebell': 'kettlebell-bulgarian-split-squat',
  'Sentadilla Búlgara en Máquina Smith': 'smith-machine-bulgarian-split',
  'Sentadilla con Banda': 'banded-squat',
  'Sentadilla con Barra en Alto': 'overhead-squat',
  'Sentadilla con Kettlebell': 'kettlebell-squat',
  'Sentadilla con Mancuernas': 'db-squat',
  'Sentadilla con Pausa': 'pause-squat',
  'Sentadilla con Peso Corporal': 'bodyweight-squat',
  'Sentadilla con Salto': 'jump-squat',
  'Sentadilla con Talones Elevados': 'heel-elevated-squat',
  'Sentadilla cosaca': 'cossack-squat',
  'Sentadilla en Caja': 'box-squat',
  'Sentadilla en Máquina Smith': 'smith-machine-squat',
  'Sentadilla en Pared': 'wall-sit',
  'Sentadilla en Pared con Pelota': 'stability-ball-wall-squat',
  'Sentadilla en Postura Dividida con Mancuernas': 'dumbbell-split-squat',
  'Sentadilla en Tijera': 'split-squat',
  'Sentadilla en Tijera en Máquina Smith': 'smith-machine-split-squat',
  'Sentadilla Frontal': 'front-squat',
  'Sentadilla Frontal con Mancuernas': 'dumbbell-front-squat',
  'Sentadilla Frontal con Pesa Rusa a Un Brazo': 'one-arm-kettlebell-front-squat',
  'Sentadilla Frontal en Máquina Smith': 'smith-machine-front-squat',
  'Sentadilla Goblet': 'goblet-squat',
  'Sentadilla Pistola con Mancuerna': 'dumbbell-pistol-squat',
  'Sentadilla pistola con pesa rusa': 'kettlebell-pistol-squat',
  'Sentadilla Pistola con TRX': 'trx-pistol-squat',
  'Sentadilla Somersault con Mancuerna': 'db-somersault-squat',
  'Sentadilla Sumo': 'sumo-squat',
  'Sentadilla Sumo con Mancuernas': 'db-sumo-squat',
  'Sentadilla Trasera con Barra': 'squat',
  'Sentadilla TRX': 'trx-squat',
  'Separación de Banda Elástica': 'band-pull-apart',
  'Skull Crusher': 'skull-crusher',
  'Skull Crusher con Mancuernas': 'db-skull-crusher',
  'Skull crusher con pesa rusa': 'kettlebell-skull-crusher',
  'Snatch con Mancuerna': 'dumbbell-snatch',
  'Spider Curl con Barra Z': 'ez-bar-spider-curl',
  'Spine Stretch Forward de Pilates': 'pilates-spine-stretch-forward',
  'Spine Twist de Pilates': 'pilates-spine-twist',
  'Split de Pie': 'standing-split',
  'Split Jerk con Dos Pesas Rusas': 'double-kettlebell-split-jerk',
  'Step Ups': 'step-ups',
  'Superman': 'superman',
  'Swing con Mancuerna a un Brazo': 'one-arm-dumbbell-swing',
  'Swing con pesa rusa': 'kettlebell-swing',
  'Swing con Pesa Rusa a Un Brazo': 'one-arm-kettlebell-swing',
  'Swing Snatch con Dos Pesas Rusas': 'double-kettlebell-swing-snatch',
  'Swing y cargada con pesa rusa': 'kettlebell-swing-clean',
  'Thruster': 'thruster',
  'Tijeras': 'scissor-kicks',
  'Toes to Bar': 'toes-to-bar',
  'Trepa de Cuerda': 'rope-climb',
  'TRX Y-Fly': 'trx-y-fly',
  'V-Ups': 'v-ups',
  'Vela con Apoyo': 'supported-shoulderstand',
  'Zancada': 'lunge',
  'Zancada Alta': 'crescent-lunge',
  'Zancada Alta Girada': 'revolved-crescent-lunge',
  'Zancada Baja': 'low-lunge',
  'Zancada Baja a Medio Split': 'low-lunge-to-half-split',
  'Zancada Caminando': 'walking-lunge',
  'Zancada con Barra': 'barbell-lunge',
  'Zancada con Mancuernas': 'db-lunge',
  'Zancada con press de pesa rusa': 'kettlebell-lunge-press',
  'Zancada Goblet con Kettlebell': 'kettlebell-goblet-lunge',
  'Zancada Inversa': 'reverse-lunge',
  'Zancada Inversa con Barra': 'barbell-reverse-lunge',
  'Zancada Inversa con Kettlebell': 'kettlebell-reverse-lunge',
  'Zancada Inversa con Peso Corporal': 'bodyweight-reverse-lunge',
  'Zancada inversa con press desequilibrado de pesa rusa': 'kettlebell-offset-reverse-lunge-and-press',
  'Zancada Inversa en Máquina Smith': 'smith-machine-reverse-lunge',
  'Zancada Lateral': 'side-lunge',
  'Zancada Pliométrica': 'plyo-lunge',
  'Zancada rotacional con pesa rusa': 'kettlebell-rotational-lunge',
  'Zancada TRX': 'trx-lunge',
};
